title: cznolan
#email: your-email@example.com
#description: >- TBD
#  TBD
#  TBD
#baseurl: ""
#url: ""
github_username: cznolan
theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#exclude:
#  - README.md
